# https://taskfile.dev

version: "3"

tasks:
  install-poetry:
    status:
      - which poetry
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 -

  install:
    sources:
      - pyproject.toml
      - poetry.lock
    deps:
      - install-poetry
    cmds:
      - poetry install

  pytest:
    deps:
      - install
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  mypy:
    deps:
      - install
    cmds:
      - >
        poetry run mypy
        --show-traceback
        --enable-incomplete-feature=Unpack
        {{.CLI_ARGS}}

  flake8:
    deps:
      - install
    cmds:
      - poetry run flake8 {{.CLI_ARGS}} .

  isort:
    deps:
      - install
    cmds:
      - poetry run isort {{.CLI_ARGS}} .

  poetry-check:
    sources:
      - pyproject.toml
    deps:
      - install-poetry
    cmds:
      - poetry check

  pip-check:
    sources:
      - pyproject.toml
      - poetry.lock
    deps:
      - install
    cmds:
      - poetry run pip check

  format:
    desc: run all code formatters
    cmds:
      - task: isort

  lint:
    desc: run all linters
    cmds:
      - task: mypy
      - task: flake8
      - task: poetry-check
      - task: pip-check

  test:
    desc: run all tests
    cmds:
      - task: pytest

  all:
    desc: run all code formatters, linters, and tests
    cmds:
      - task: format
      - task: lint
      - task: test
